language: go
services: docker

go:
- 1.12

# TODO: Builds for other branches

jobs:
  include:
    - stage: build_master
      on:
        branch: master
      script: 
        - make docker_build
        - make docker_test
        - make docker_build_release
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make docker_push_release

