language: go
services: docker

go:
- 1.16

# TODO: Builds for other branches

jobs:
  include:
    - stage: build
      script: 
        - make docker_build
        - make docker_test
    - stage: release
      on:
        branch: master
      script: 
        - make docker_build_release
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make docker_push_release

